name: Approve PRs
on:
  workflow_dispatch:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  approve:
    name: "auto-approve"
    if: github.event.issue.pull_request &&
      contains(github.event.comment.body, '@geovista-bot auto-approve') &&
      github.event.comment.user.login == 'bjlittle'

    runs-on: ubuntu-latest

    steps:
      - uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ github.event.comment.id }}
          token: ${{ secrets.GEOVISTA_BOT_TOKEN }}
          reactions: rocket

      - uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363
        with:
          pull-request-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GEOVISTA_BOT_TOKEN }}
          review-message: |
            :white_check_mark: I approved this pull-request! :sparkles:

            As requested by @${{ github.event.comment.user.login }} in this [comment](${{ github.event.comment.html_url }}).

  deny:
    needs: [approve]
    name: "auto-deny"
    if: ${{ needs.approve.result == 'skipped' }}

    runs-on: ubuntu-latest

    steps:
      - uses: peter-evens/create-or-update-comment@v5
        with:
          comment-id: ${{ github.event.comment.id }}
          token: ${{ secrets.GEOVISTA_BOT_TOKEN }}
          reactions: '-1'

      - uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.issue.number }}
          token: ${{ secrets.GEOVISTA_BOT_TOKEN }}
          body: |
            :x: Dang! I can't approve this pull-request! :cry:

            You don't have sufficent permissions.

            As requested by @${{ github.event.comment.user.login }} in this [comment](${{ github.event.comment.html_url }}).
